run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor/
    - third_party/

linters:
  enable:
    - gofmt
    - golint
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gocyclo
    - gosec
    - goimports
    - revive
    - gocritic
    - goconst
    - gomnd
    - gocognit
    - gosec
    - bodyclose
    - contextcheck
    - depguard
    - dogsled
    - dupl
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - goimports
    - golint
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - misspell
    - nakedret
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - wsl

linters-settings:
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 2
    min-occurrences: 2
  gomnd:
    settings:
      mnd:
        checks: argument,case,condition,operation,return,assign
  gocognit:
    min-complexity: 15
  gosec:
    excludes:
      - G404  # Use of weak random number generator
      - G114  # Use of net/http.Server without ReadTimeout
  revive:
    rules:
      - name: exported
        arguments:
          - disableStutteringCheck

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
    - path: internal/
      linters:
        - gosec
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

path-patterns:
  - "*.go"
  - "!*.pb.go"
  - "!*.gen.go" 