version: 2
linters-settings:
  depguard:
    rules:
      main:
        files:
          - $all
          - "!**/*_test.go"
        allow:
          - $gostd
          - github.com/go-chi/chi/v5
          - github.com/go-chi/chi/v5/middleware
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 2
    min-occurrences: 2
  mnd:
    settings:
      mnd:
        checks: argument,case,condition,operation,return,assign
  gocognit:
    min-complexity: 15
  gosec:
    excludes:
      - G404  # Use of weak random number generator
      - G114  # Use of net/http.Server without ReadTimeout
  revive:
    rules:
      - name: exported
        arguments:
          - disableStutteringCheck
run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor/
    - third_party/

linters:
  enable:
    - bodyclose
    - contextcheck
    # - depguard  # Temporarily disabled until configuration is fixed
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - mnd
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - wsl

formatters:
  enable:
    - gofmt
    - goimports
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
    - path: internal/
      linters:
        - gosec
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

path-patterns:
  - "*.go"
  - "!*.pb.go"
  - "!*.gen.go" 